const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let current='world',progress=72,done=0,attention=1,workLayout='auto';
const crumb=$('#crumb'),context=$('#context'),menu=$('#menu'),menuScrim=$('#menuScrim'),dialog=$('#dialog'),dialogScrim=$('#dialogScrim');
function sync(){ $('#progressStat').textContent=progress+'%'; $('#doneStat').textContent=`DONE ${done}/3`; $('#ctxProg').style.width=progress+'%';$('#ctxProgN').textContent=progress;$('#ctxAtt').style.width=(attention*20)+'%';$('#ctxAttN').textContent=attention;$('#workProg').style.width=progress+'%';$('#workProgN').textContent=progress;$('#workAtt').style.width=(attention*20)+'%';$('#workAttN').textContent=attention;$('#workDone').style.width=(done/3*100)+'%';$('#workDoneN').textContent=`${done}/3`;}
function closeModes(){ $$('.mode').forEach(x=>x.classList.remove('on')); current='world'; crumb.textContent='WORLD / KINDLE SHELL'; $$('.dockBtn[data-mode]').forEach(x=>x.classList.toggle('on',x.dataset.mode==='world')); }
function openMode(id){ closeMenu(); closeContext(); closeDialog(); $$('.mode').forEach(x=>x.classList.remove('on')); if(id==='world'){closeModes();return} const m=$('#'+id); if(m)m.classList.add('on'); current=id; crumb.textContent=id.toUpperCase(); $$('.dockBtn[data-mode]').forEach(x=>x.classList.toggle('on',x.dataset.mode===id)); if(id==='work')arrangeWork(); }
function openMenu(){closeContext();menuScrim.classList.add('on');menu.classList.add('on')}
function closeMenu(){menuScrim.classList.remove('on');menu.classList.remove('on')}
function openContext(){closeMenu();context.style.display='block'} function closeContext(){context.style.display='none'}
function openDialog(){dialogScrim.classList.add('on');dialog.classList.add('on')}function closeDialog(){dialogScrim.classList.remove('on');dialog.classList.remove('on')}
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>openMode(b.dataset.mode)));$$('[data-open-menu]').forEach(b=>b.onclick=openMenu);$$('[data-close-menu]').forEach(b=>b.onclick=closeMenu);menuScrim.onclick=closeMenu;$('#handle').onclick=openContext;$$('[data-open-context]').forEach(b=>b.onclick=()=>{closeMenu();openContext()});$$('[data-close-context]').forEach(b=>b.onclick=closeContext);$$('[data-open-dialog]').forEach(b=>b.onclick=()=>{closeMenu();openDialog()});$$('[data-close-dialog]').forEach(b=>b.onclick=closeDialog);dialogScrim.onclick=closeDialog;$$('[data-close-mode]').forEach(b=>b.onclick=closeModes);
$('#fullBtn').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen({navigationUI:'hide'});else await document.exitFullscreen()}catch(e){}};document.addEventListener('pointerdown',()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.({navigationUI:'hide'}).catch(()=>{})},{once:true});
function productive(){progress=Math.min(96,progress+8);done=Math.min(3,done+1);attention=0;sync();const t=$('#wTask .task.sel small');if(t)t.textContent='✓ completado · output integrado';}
$('[data-demo="ctx-run"]').onclick=productive;$('[data-demo="dialog-accept"]').onclick=()=>{productive();closeDialog()};
$('[data-demo="chat-send"]').onclick=()=>{const i=$('#chatInput'); if(i.value.trim()){const div=document.createElement('div');div.className='msg me';div.innerHTML=`<div class="avatar">YO</div><div class="bubble">${i.value.replace(/[<>]/g,'')}<div class="msgMeta">ahora</div></div>`;$('.thread').appendChild(div);i.value='';}};
const winIds=['wTask','wStatus','wChat','wReader'];function openWork(id){$('#'+id).style.display='block';arrangeWork()}function closeWork(id){$('#'+id).style.display='none';arrangeWork()}$$('[data-wclose]').forEach(b=>b.onclick=()=>closeWork(b.dataset.wclose));$('[data-demo="work-task"]').onclick=()=>openWork('wTask');$('[data-demo="work-status"]').onclick=()=>openWork('wStatus');$('[data-demo="work-chat"]').onclick=()=>openWork('wChat');$('[data-demo="work-reader"]').onclick=()=>openWork('wReader');$$('[data-work-layout]').forEach(b=>b.onclick=()=>{workLayout=b.dataset.workLayout;$$('[data-work-layout]').forEach(x=>x.classList.toggle('on',x===b));arrangeWork()});
function arrangeWork(){const d=$('#workDesk'),wins=winIds.map(id=>$('#'+id)).filter(x=>getComputedStyle(x).display!=='none');const W=d.clientWidth,H=d.clientHeight,g=10;if(!wins.length)return;if(workLayout==='focus'){wins.forEach((w,i)=>Object.assign(w.style,i===0?{left:g+'px',top:g+'px',width:(W-2*g)+'px',height:(H-2*g)+'px'}:{left:(W-220-g)+'px',top:(g+i*42)+'px',width:'210px',height:'120px'}));return}if(workLayout==='grid'){const cols=W/H>1.1?2:1,rows=Math.ceil(wins.length/cols),cw=(W-g*(cols+1))/cols,ch=(H-g*(rows+1))/rows;wins.forEach((w,i)=>Object.assign(w.style,{left:(g+(i%cols)*(cw+g))+'px',top:(g+Math.floor(i/cols)*(ch+g))+'px',width:cw+'px',height:ch+'px'}));return}if(W/H>1.1){if(wins.length===1)Object.assign(wins[0].style,{left:g+'px',top:g+'px',width:(W-2*g)+'px',height:(H-2*g)+'px'});else{const main=wins[0];Object.assign(main.style,{left:g+'px',top:g+'px',width:(W*.64-g*1.5)+'px',height:(H-2*g)+'px'});const sw=W*.36-g*1.5,sh=(H-g*wins.length)/(wins.length-1);wins.slice(1).forEach((w,i)=>Object.assign(w.style,{left:(W*.64+g*.5)+'px',top:(g+i*(sh+g))+'px',width:sw+'px',height:sh+'px'}));}}else{const main=wins[0];Object.assign(main.style,{left:g+'px',top:g+'px',width:(W-2*g)+'px',height:(H*.62-g*1.5)+'px'});const rest=wins.slice(1),sh=(H*.38-g*(rest.length+1))/Math.max(rest.length,1);rest.forEach((w,i)=>Object.assign(w.style,{left:g+'px',top:(H*.62+g*.5+i*(sh+g))+'px',width:(W-2*g)+'px',height:Math.max(100,sh)+'px'}));}}
addEventListener('resize',()=>{if(current==='work')arrangeWork()});
const demoBtn=$('#demoBtn'),pauseBtn=$('#demoPause'),speedBtn=$('#demoSpeed'),cap=$('#demoCaption'),cur=$('#cursor'),mouse=$('#mouse'),ml=$('#mouse .l'),pulse=$('#pulse');let demoRunning=false,demoAbort=false,demoPaused=false,demoSpeed=1;const wait=ms=>new Promise(r=>setTimeout(r,ms/demoSpeed));async function gate(){while(demoPaused&&!demoAbort)await new Promise(r=>setTimeout(r,80))}
function pos(el){const r=el.getBoundingClientRect();return{x:r.left+r.width*.55,y:r.top+r.height*.55}}
async function moveTo(el,hand=true){if(!el)return;await gate();const p=pos(el);cur.classList.add('on');cur.classList.toggle('hand',hand);mouse.classList.add('on');cur.style.transform=`translate(${p.x-12}px,${p.y-10}px)`;await wait(520)}
async function clickDemo(el,text){if(!el)return;cap.textContent=text||'';cap.classList.toggle('on',!!text);await moveTo(el,true);const p=pos(el);cur.classList.add('press');ml.classList.add('down');pulse.style.left=p.x+'px';pulse.style.top=p.y+'px';pulse.classList.remove('on');void pulse.offsetWidth;pulse.classList.add('on');await wait(180);el.click();cur.classList.remove('press');ml.classList.remove('down');await wait(650)}
async function typeDemo(el,text){cap.textContent='Escribo en el input universal.';cap.classList.add('on');await moveTo(el,false);el.focus();for(const ch of text){if(demoAbort)break;el.value+=ch;await wait(55)}}
async function runDemo(){if(demoRunning)return;demoRunning=true;demoAbort=false;demoPaused=false;demoBtn.textContent='STOP';closeModes();closeMenu();closeContext();closeDialog();const steps=[
()=>clickDemo($('[data-demo="context-handle"]'),'Abro CONTEXTO sin abandonar la escena fullscreen.'),
()=>clickDemo($('[data-demo="ctx-run"]'),'Ejecuto un bloque real: sube progreso y aparece DONE.'),
()=>clickDemo($('[data-close-context]'),'Cierro contexto y recupero la escena limpia.'),
()=>clickDemo($('[data-demo="menu-btn"]'),'Abro el MENÚ como pausa, no como navbar permanente.'),
()=>clickDemo($('[data-demo="menu-dialog"]'),'Abro una DECISIÓN temporal.'),
()=>clickDemo($('[data-demo="dialog-accept"]'),'Confirmo y vuelvo exactamente al shell.'),
()=>clickDemo($('[data-demo="chat-btn"]'),'Entro a CHAT, que usa otra composición.'),
()=>typeDemo($('#chatInput'),'Resultado listo'),
()=>clickDemo($('[data-demo="chat-send"]'),'Envío el mensaje desde el input universal.'),
()=>clickDemo($('#chat [data-close-mode]'),'Cierro CHAT.'),
()=>clickDemo($('[data-demo="read-btn"]'),'Abro READER: el contenido domina la pantalla.'),
()=>clickDemo($('#reader [data-close-mode]'),'Cierro READER y vuelvo al WORLD.'),
()=>clickDemo($('[data-demo="menu-btn"]'),'Abro MENÚ otra vez.'),
()=>clickDemo($('[data-demo="menu-work"]'),'Entro a WORKSPACE, donde sí viven las ventanas.'),
()=>clickDemo($('[data-demo="work-status"]'),'Abro STATUS y el tiler reorganiza el espacio.'),
()=>clickDemo($('[data-demo="work-chat"]'),'Abro CHAT como herramienta secundaria.'),
()=>clickDemo($('#wChat [data-wclose]'),'Cierro CHAT cuando ya no lo necesito.'),
()=>clickDemo($('[data-work-layout="focus"]'),'FOCUS prioriza la tarea actual.'),
()=>clickDemo($('[data-work-layout="auto"]'),'AUTO devuelve el layout productivo.'),
()=>clickDemo($('#work [data-close-mode]'),'Salgo de WORKSPACE y regreso al WORLD limpio.')
];for(const s of steps){if(demoAbort)break;await gate();await s()}cap.classList.remove('on');cur.classList.remove('on');mouse.classList.remove('on');demoBtn.textContent='DEMO';demoRunning=false}
demoBtn.onclick=()=>{if(demoRunning){demoAbort=true;demoBtn.textContent='DEMO'}else runDemo()};pauseBtn.onclick=()=>{demoPaused=!demoPaused;pauseBtn.textContent=demoPaused?'▶':'Ⅱ'};speedBtn.onclick=()=>{demoSpeed=demoSpeed===1?2:1;speedBtn.textContent=demoSpeed+'×'};document.addEventListener('pointerdown',e=>{if(demoRunning&&e.isTrusted&&!e.target.closest('#demoPanel'))demoAbort=true},{capture:true});sync();arrangeWork();