(function(){
'use strict';
const root=document.querySelector('#labRoot'),q=s=>root.querySelector(s);
const stateText=q('#stateText'),modal=q('[data-demo-id="modal"]'),toast=q('[data-demo-id="toast"]'),card=q('[data-demo-id="card.drag"]'),drop=q('[data-demo-id="drop.zone"]'),transform=q('[data-demo-id="box.transform"]');
const _pointers=window.DEMO_ENGINE_V4_POINTERS||{};const pointerAssets={arrow:{src:_pointers.arrow,hotspot:[9,8],size:52},hand:{src:_pointers.hand,hotspot:[24,5],size:52},grab:{src:_pointers.grab,hotspot:[26,22],size:52},grabbing:{src:_pointers.grabbing,hotspot:[26,22],size:52},text:{src:_pointers.text,hotspot:[26,26],size:52},'resize-ew':{src:_pointers['resize-ew'],hotspot:[26,26],size:52},'resize-ns':{src:_pointers['resize-ns'],hotspot:[26,26],size:52},'resize-d1':{src:_pointers['resize-d1'],hotspot:[26,26],size:52},forbidden:{src:_pointers.forbidden,hotspot:[26,26],size:52}};
const _gestures=window.DEMO_ENGINE_V4_GESTURES||{};const gestureAssets={wave:_gestures.wave,approve:_gestures.thumb_up,reject:_gestures.thumb_down,snap:_gestures.snap,ok:_gestures.ok,stop:_gestures.palm,point:_gestures.point,move:_gestures.move_hand,victory:_gestures.victory,fist:_gestures.fist};
q('[data-demo-id="modal.open"]').addEventListener('click',()=>{modal.hidden=false;stateText.textContent='modal open';});q('[data-demo-id="modal.close"]').addEventListener('click',()=>{modal.hidden=true;stateText.textContent='modal closed';});q('[data-demo-id="toast.show"]').addEventListener('click',()=>{toast.hidden=false;stateText.textContent='saved';setTimeout(()=>toast.hidden=true,1900);});q('[data-demo-id="menu.open"]').addEventListener('click',()=>stateText.textContent='menu action');q('[data-demo-id="chat.send"]').addEventListener('click',()=>stateText.textContent='sent: '+q('[data-demo-id="chat.input"]').value);drop.addEventListener('drop',()=>{drop.textContent='RECIBIDO ✓';card.textContent='MOVIDO';stateText.textContent='drag complete';});
const observer=new DemoObserver(),quality=q('#quality'),receipts=q('#receipts');let group=null;
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
observer.on(r=>{
  if(r.type==='quality_gate'){quality.className='quality '+(r.pass?'pass':'fail');quality.textContent=r.pass?'Motion quality gate: PASS':'Motion quality gate: FAIL · '+r.issues.map(x=>x.code).join(', ');}
  if(r.type==='step_start'){group=document.createElement('details');group.className='receipt-group';group.open=false;group.innerHTML=`<summary>${esc(String(r.action).toUpperCase())}${r.target?' · '+esc(r.target):''}</summary><div class="receipt-events"></div>`;receipts.prepend(group);return;}
  if(r.type==='step_end'&&group){group.classList.add('pass');return;}
  if(r.type==='run_error'&&group){group.classList.add('fail');group.open=true;}
  if(group){const row=document.createElement('div');row.textContent=r.type+(r.target?' · '+r.target:'');group.querySelector('.receipt-events').appendChild(row);}
});
function resetWorld(){modal.hidden=true;toast.hidden=true;stateText.textContent='idle';drop.textContent='SOLTAR ACÁ';drop.classList.remove('drop-active');card.textContent='ARRASTRAME';card.style.transform='';card.classList.remove('is-dragging');transform.style.transform='';transform.style.width='';transform.style.height='';q('[data-demo-id="chat.input"]').value='';q('[data-demo-id="opt.toggle"]').checked=false;q('[data-demo-id="opt.select"]').value='A';q('[data-demo-id="opt.slider"]').value='35';q('[data-demo-id="scroll.box"]').scrollTop=0;}
const engine=new DemoEngineV4(root,{title:'ENGINE V4',steps:[]},{observer,abortOnHuman:false,preset:'TEACH',pointerAssets,gestureAssets,onReset:resetWorld});
const scripts={
 pointer:{title:'Pointer continuity',steps:[{intent:'explain',say:'Cada viaje tiene origen, trayecto, llegada, press y tiempo para mirar.',hold:900},{action:'look',target:'menu.open',hold:850},{action:'click',target:'menu.open',guide:'laser'},{action:'look',target:'toast.show',hold:650},{action:'click',target:'toast.show',guide:'laser'},{action:'visualHold',ms:900}]},
 space:{title:'Spatial actions',steps:[{intent:'explain',say:'Scroll, drag y resize ahora explican físicamente qué está pasando.',hold:900},{action:'scroll',target:'scroll.box',toTarget:'scroll.goal'},{action:'visualHold',ms:700},{action:'drag',from:'card.drag',to:'drop.zone',duration:1050,guide:'laser'},{action:'visualHold',ms:850},{action:'resize',target:'box.transform',width:250,height:150,duration:1000,guide:'arrow'},{action:'visualHold',ms:800}]},
 camera:{title:'Show without clicking',steps:[{intent:'explain',say:'LOOK muestra; TRACE dibuja el perímetro; camera focus mantiene unido cursor y target.',hold:950},{action:'look',target:'chat.input',hold:1000},{action:'trace',target:'chat.input',segmentDuration:390,hold:650},{action:'cameraFocus',target:'chat.input',scale:1.10,hold:1050},{action:'comment',target:'chat.input',text:'La explicación queda cerca, pero nunca encima del target.',hold:1100}]},
 logic:{title:'Observer',steps:[{intent:'explain',say:'Después de actuar, el motor espera la reacción real y recién entonces sigue.',hold:900},{action:'click',target:'modal.open'},{action:'waitFor',condition:{target:'modal',visible:true,timeout:1800}},{action:'assert',condition:{target:'modal',visible:true},message:'El modal debería estar visible'},{action:'look',target:'modal',hold:900},{action:'click',target:'modal.close'},{action:'visualHold',ms:700}]},
 narrative:{title:'Narrative',steps:[{intent:'explain',say:'Gestos y comentarios son eventos narrativos, no cursores permanentes.',hold:950},{action:'look',target:'comment.anchor',hold:650},{action:'comment',target:'comment.anchor',text:'Comentario anclado con zona segura.',tone:'good',hold:1200},{action:'gesture',name:'point',target:'comment.anchor',hold:1000},{action:'gesture',name:'ok',target:'comment.anchor',hold:950}]}
};
const all={title:'MOTION DIRECTOR V4',steps:[{action:'narrate',say:'Primero: continuidad del puntero.',hold:750},...scripts.pointer.steps,{action:'narrate',say:'Ahora: acciones espaciales.',hold:750},...scripts.space.steps,{action:'narrate',say:'Después: mostrar sin hacer click.',hold:750},...scripts.camera.steps,{action:'narrate',say:'Finalmente: observer y narración.',hold:750},...scripts.logic.steps,...scripts.narrative.steps]};
function run(script){engine.stop('switch');engine.setScript(script);engine.reset();receipts.innerHTML='';group=null;quality.className='quality';quality.textContent='Motion quality gate corriendo…';q('#debugPanel').classList.remove('on');q('#debugToggle').textContent='Debug';engine.play(0);}
q('#runAll').addEventListener('click',()=>run(all));q('#pause').addEventListener('click',()=>engine.pause());q('#resume').addEventListener('click',()=>engine.resume());q('#reset').addEventListener('click',()=>engine.reset());root.querySelectorAll('[data-cap]').forEach(b=>b.addEventListener('click',()=>run(scripts[b.dataset.cap])));q('#debugToggle').addEventListener('click',e=>{const on=q('#debugPanel').classList.toggle('on');e.currentTarget.textContent=on?'Hide debug':'Debug';});q('#presets').querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{q('#presets').querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');engine.setPreset(b.dataset.preset);}));engine.pointerMode('arrow');window.engine=engine;window.DEMO_ENGINE_V4_ASSETS={pointerAssets,gestureAssets};
})();