import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.114.0/+esm';
const URL='https://catnohyouxqjjtseaueb.supabase.co';
const KEY='sb_publishable_eqh3PngXs4UjLLWiY3pz1w_nhHtf7X-';
const ROOM='casa-amigos-v1';
const supabase=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const $=s=>document.querySelector(s);
const el={join:$('#joinView'),chat:$('#chatView'),nameForm:$('#nameForm'),name:$('#nameInput'),joinError:$('#joinError'),form:$('#messageForm'),input:$('#messageInput'),send:$('#sendButton'),messages:$('#messages'),empty:$('#empty'),people:$('#people'),count:$('#onlineCount'),mobileCount:$('#mobileCount'),status:$('#status'),leave:$('#leaveButton')};
let channel=null,connected=false,currentName='',lastSend=0;
const clientId=sessionStorage.getItem('casa_client_id')||crypto.randomUUID();
sessionStorage.setItem('casa_client_id',clientId);
el.name.value=localStorage.getItem('casa_name')||'';
const clean=v=>v.replace(/\s+/g,' ').trim().slice(0,24);
const initials=n=>n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?';
function color(v){let h=0;for(const c of v)h=c.charCodeAt(0)+((h<<5)-h);return`hsl(${Math.abs(h)%360} 38% 48%)`}
function setStatus(ok,text){connected=ok;el.status.classList.toggle('online',ok);el.status.querySelector('span').textContent=text;el.input.disabled=!ok;el.send.disabled=!ok;if(ok)queueMicrotask(()=>el.input.focus())}
function time(iso){return new Intl.DateTimeFormat('es-AR',{hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}
function addMessage(m){if(!m||typeof m.text!=='string'||typeof m.name!=='string')return;const text=m.text.trim().slice(0,500),name=clean(m.name);if(!text||!name)return;el.empty?.remove();const row=document.createElement('article');row.className='message'+(m.clientId===clientId?' mine':'');const avatar=document.createElement('div');avatar.className='avatar';avatar.style.background=color(m.clientId||name);avatar.textContent=initials(name);const body=document.createElement('div');body.className='body';const meta=document.createElement('div');meta.className='meta';const who=document.createElement('b');who.textContent=m.clientId===clientId?'Vos':name;const when=document.createElement('span');when.textContent=time(m.sentAt||new Date().toISOString());meta.append(who,when);const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=text;body.append(meta,bubble);row.append(avatar,body);el.messages.append(row);while(el.messages.querySelectorAll('.message').length>100)el.messages.querySelector('.message')?.remove();el.messages.scrollTop=el.messages.scrollHeight}
function renderPeople(){if(!channel)return;const seen=new Map();for(const item of Object.values(channel.presenceState()).flat()){if(item?.clientId&&item?.name)seen.set(item.clientId,{clientId:item.clientId,name:clean(item.name)})}const list=[...seen.values()].sort((a,b)=>a.clientId===clientId?-1:b.clientId===clientId?1:a.name.localeCompare(b.name,'es'));el.people.replaceChildren();for(const p of list){const row=document.createElement('div');row.className='person'+(p.clientId===clientId?' me':'');const avatar=document.createElement('div');avatar.className='avatar';avatar.style.background=color(p.clientId);avatar.textContent=initials(p.name);const txt=document.createElement('div');txt.className='personText';const b=document.createElement('b');b.textContent=p.name;const s=document.createElement('span');s.textContent=p.clientId===clientId?'vos':'online';txt.append(b,s);const dot=document.createElement('i');dot.className='dot';row.append(avatar,txt,dot);el.people.append(row)}el.count.textContent=`${list.length} online`;el.mobileCount.textContent=`${list.length} online`}
async function enter(name){currentName=name;localStorage.setItem('casa_name',name);el.joinError.textContent='';el.join.classList.add('hidden');el.chat.classList.remove('hidden');setStatus(false,'Conectando…');channel=supabase.channel(ROOM,{config:{broadcast:{self:true,ack:true},presence:{key:clientId}}});channel.on('broadcast',{event:'message'},({payload})=>addMessage(payload)).on('presence',{event:'sync'},renderPeople).subscribe(async status=>{if(status==='SUBSCRIBED'){const tracked=await channel.track({clientId,name:currentName,joinedAt:new Date().toISOString()});if(tracked!=='ok'){setStatus(false,'Error de presencia');return}setStatus(true,'Conectado');renderPeople()}else if(status==='CHANNEL_ERROR')setStatus(false,'Error de conexión');else if(status==='TIMED_OUT')setStatus(false,'Reintentando…');else if(status==='CLOSED')setStatus(false,'Desconectado')})}
async function leave(){setStatus(false,'Saliendo…');if(channel){try{await channel.untrack()}catch{}try{await supabase.removeChannel(channel)}catch{}}channel=null;el.people.replaceChildren();el.messages.replaceChildren();const empty=document.createElement('div');empty.id='empty';empty.className='empty';const b=document.createElement('b');b.textContent='La casa está tranquila.';const s=document.createElement('span');s.textContent='Mandá el primer mensaje.';empty.append(b,s);el.messages.append(empty);el.empty=empty;el.chat.classList.add('hidden');el.join.classList.remove('hidden');el.name.value=currentName;el.name.focus()}
el.nameForm.addEventListener('submit',e=>{e.preventDefault();if(channel)return;const name=clean(el.name.value);if(!name){el.joinError.textContent='Poné un nombre para entrar.';return}enter(name)});
el.form.addEventListener('submit',async e=>{e.preventDefault();if(!connected||!channel)return;const text=el.input.value.trim().slice(0,500);if(!text)return;const now=Date.now();if(now-lastSend<350)return;lastSend=now;el.input.value='';el.input.focus();const result=await channel.send({type:'broadcast',event:'message',payload:{id:crypto.randomUUID(),clientId,name:currentName,text,sentAt:new Date().toISOString()}});if(result!=='ok'){el.input.value=text;setStatus(false,'No se pudo enviar')}});
el.leave.addEventListener('click',leave);
el.mobileCount.addEventListener('click',()=>{const names=[...el.people.querySelectorAll('.personText b')].map(x=>x.textContent).join(', ');alert(names?`Online: ${names}`:'Todavía no hay nadie online.')});
window.addEventListener('beforeunload',()=>{try{channel?.untrack()}catch{}});
el.name.focus();