const CACHE='casa-v4';
const APP_SHELL=['./','./index.html','./style.css','./app.js','./manifest.webmanifest','./icon.svg'];
const DB_NAME='casa-push',STORE='pending';
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(APP_SHELL)).catch(()=>{}))});
self.addEventListener('activate',event=>{event.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k))))]))});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;if(event.request.mode==='navigate'){event.respondWith(fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put('./index.html',copy)).catch(()=>{});return response}).catch(()=>caches.match('./index.html').then(r=>r||caches.match('./'))));return}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(event.request,response.clone())).catch(()=>{});return response})))});
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'messageId'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function savePending(data){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(data);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
self.addEventListener('push',event=>{let data={};try{data=event.data?.json()||{}}catch{try{data=JSON.parse(event.data?.text()||'{}')}catch{}}if(data.type!=='casa-message')return;event.waitUntil((async()=>{try{await savePending(data)}catch{}try{await self.registration.setAppBadge?.()}catch{}const icon=new URL('./icon.svg',self.registration.scope).href;await self.registration.showNotification(`CASA · ${data.name||'Mensaje'}`,{body:data.text||'Nuevo mensaje',icon,badge:icon,tag:`casa-${data.messageId||Date.now()}`,renotify:true,silent:false,vibrate:[120,70,120],data})})())});
self.addEventListener('notificationclick',event=>{event.notification.close();const data=event.notification.data||{};event.waitUntil((async()=>{const windows=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of windows){if('focus'in client){await client.focus();client.postMessage({type:'casa-push-open',payload:data});return}}const target=new URL(`./?push=${encodeURIComponent(data.messageId||'')}`,self.registration.scope).href;if(self.clients.openWindow)await self.clients.openWindow(target)})())});